# Disable the image optimization pipeline for the local development
# environment.
skip_missing_workers: true
advpng: false
gifsicle: false
jhead: false
jpegoptim: false
jpegtran: false
optipng: false
pngquant: false
pngout: false
pngcrush: false
svgo: false
